### ISSUE TITLE
Enable compression on CDN

### ISSUE THREAD

**Issue by prabinv** [GoogleChromeLabs/payment-request-shim#12]
We are using the payment-request-shim in our application, and we are in the process of optimizing it for performance. The recommendations from Pagespeed Insights is to enable gzip compression on the files, and one of them is the payment-request-shim script. is it possible to have this script gzipped, and uploaded to GCP storage with the Content-Encoding set as `gzip`?

https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#content-encoding

Since most of the browsers support gzip, do you think it will cause any issues?

**Comment by agektmr** [comment]
@prabinv sorry for lagged response. I think this should be possible. Let me investigate further.

**Comment by prabinv** [comment]
Awesome. Thanks for the response @agektmr. Do let me know if I can do anything.

**Comment by agektmr** [comment]
@prabinv the deployed shim should now be gzipped.
