### ISSUE TITLE
Does this script allow async?

### ISSUE THREAD

**Issue by omvaishnav** [GoogleChromeLabs/payment-request-shim#9]
I am implementing this payment API but I want to add async to this script so is it allow async like following?
<script src="https://storage.googleapis.com/prshim/v1/payment-shim.js" async></script>

**Comment by gauntface** [comment]
You should be able to use this async but you'll need to make sure that you don't use the PaymentRequest API until after the script has loaded (via the load event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement)
